- name: restart services
  hosts: all
  become: true
  tasks:
    - name: sshd restart
      ansible.builtin.service:
        name: sshd
        state: restarted
        enabled: true
    - name: sshd restart
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
    - name: sshd restart
      ansible.builtin.service:
        name: ntpd
        state: restarted
        enabled: true